### ISSUE TITLE
Introduce bias terms

### ISSUE THREAD

**Issue by dafnevk** [carpentries-incubator/deep-learning-intro#111]
In episode 4, we take a close look at the number of parameters of the different type of layers. To understand where the number of parameters comes from, it is important to know that neurons have a bias term, in addition to the weight parameters. The bias term is not mentioned in episode 4. I think it should either be introduced there, or episode 4 needs a recap of the calculation within a neuron, also explaining the bias term.

**Comment by dafnevk** [comment]
What would also help very much is an image of a single neuron, that shows how inputs, weights and biases are combined in a sum and activation.

**Comment by bpmweel** [comment]
For Image of a neuron see #121
