### ISSUE TITLE
Improve AI/DL/ML field figure

### ISSUE THREAD

**Issue by bpmweel** [carpentries-incubator/deep-learning-intro#115]
This image could be improved by showing in the image some of the common techniques in each of the sections.

Perhaps another image like this one would also help with situating deep learning in the ML and AI fields

![](https://lawtomated.com/wp-content/uploads/2019/04/MLvsDL.png)

**Comment by colinsauze** [comment]
Is this your own image, if not do you have a source for it?

**Comment by colinsauze** [comment]
This was solved in PR #139
