### ISSUE TITLE
List of background resources

### ISSUE THREAD

**Issue by bpmweel** [carpentries-incubator/deep-learning-intro#116]
A list of further material for the learners would be helpful. We should make a list of documentation, videos, blogposts and or papers that learners can use after each episode.

Perhaps we can also add some material that learners can optionally review before the workshop, but it should not be mandatory.

- Add a further reading section to each episode
- See if we can automate adding this to an extras page

**Comment by bpmweel** [comment]
From our collaborative documents:

Episode 1 & 2:
Keras Documentation: https://keras.io/api/
Issues with Apple M1 --> https://medium.com/codex/installing-tensorflow-on-m1-macs-958767a7a4b3

Episode 3:
On unbalanced data: https://towardsdatascience.com/handling-imbalanced-datasets-in-deep-learning-f48407a0e758
And this tutorial to apply this in Keras: https://www.tensorflow.org/tutorials/structured_data/imbalanced_data
A nice tool for visualising the model as well as model training is: https://www.tensorflow.org/tensorboard (it comes with tensor flow)

A really good and popular hands-on online course on deep learning: https://course.fast.ai/
Being able to run deep learning models on GPU is key in applying it in practice (because your experiment cycle is shortened a lot (i.e. minutes instead of hours/days)), so get access to a GPU in the cloud (for example with google colab) and try to run keras on GPU
A great very practical easy-to-read (I would say page-turner) on machine learning (and deep learning) in practice: Machine Learning Yearning by Andrew Ng. Also has very good tips for data hygiene!
A really thorough, detailed (though math-heavy) book on everything (for example Generative Adverserial Networks or Autoencoders) you want to know about deep learning: Deep learning, Goodfellow et al.
Stay up-to-date with recent ML/DL papers, for example using arxiv sanity preserver

**Comment by dsmits** [comment]
Related: #163

**Comment by dsmits** [comment]
I'd say we add these links to the end of the relevant episodes. Teachers can paste them in the collaborative document during teaching

**Comment by CunliangGeng** [comment]
Dafne already add the links in PR #239.
