### ISSUE TITLE
introductory slidedeck

### ISSUE THREAD

**Issue by psteinb** [carpentries-incubator/deep-learning-intro#121]
To set the scene, we currently have episode 1 which is rather heavy on text. We have reason to believe that a simple slidedeck with (a lot of) images mostly that addresses the learning goals of episode 1.

For this, we might experiment with rmarkdown that the current setup can render.
`rmarkdown` supports rendering slides:  https://rmarkdown.rstudio.com/lesson-11.html

**Comment by bpmweel** [comment]
Here are the slides I used at the previous workshop.

[DL Slides.pptx](https://github.com/carpentries-incubator/deep-learning-intro/files/6790964/DL.Slides.pptx)

**Comment by colinsauze** [comment]
do you have a reference for the source of the image on slide 5 (difference between AI, ML and DL)? I can find a few instances of this on google images but can't work out the original source.

**Comment by psteinb** [comment]
Ok, I was digging into this today. So in principle, one could use Rmarkdown to create presentations, e.g. based on a [reveal.js](https://bookdown.org/yihui/rmarkdown/revealjs.html).

**But** the carpentries template does nothing else, than to convert the Rmarkdown first in order to hand it over to jekyll for rendering. That means, that my idea to use the `_episodes_rmd` folder to carve a presentation won't work this way.

**Comment by psteinb** [comment]
We could revert to using a gem to integrate reveal.js slidedecks into our jekyll build:
https://sylhare.github.io/2020/09/09/easy-presentation-reveal.js-with-jekyll.html
But I have the feeling that his might inflict quite some diversion from the main carpentries' lesson template.

**Comment by dsmits** [comment]
This is nice to have, not sure if it is within the scope of a carpentries lesson. Since this issue is quite stale, I'm closing it now, feel free to reopen if you disagree @psteinb
