### ISSUE TITLE
Add relevant images to episode 2

### ISSUE THREAD

**Issue by bpmweel** [carpentries-incubator/deep-learning-intro#125]
The slide deck has some nice images that support the explanations, they should be added to episode 2.

- [ ] Add Images
- [ ] Add note to instructor notes that you can copy paste images into a notebook.

See also:
- #98 
- #111

**Comment by psteinb** [comment]
Not sure what we need explicitly. Just wanting to drop some resources we could draw from:
- https://betterimagesofai.org/images (high level)
- https://github.com/dvgodoy/dl-visuals (lots details contained sometime)

**Comment by dsmits** [comment]
Slide deck can be found at issue #121

**Comment by dsmits** [comment]
Stale issue
