### ISSUE TITLE
Move comparison to baseline 

### ISSUE THREAD

**Issue by dafnevk** [carpentries-incubator/deep-learning-intro#132]
The comparison with a baseline method is now done quite towards the end of episode 3. In practice, a baseline is something you often start with before applying more advanced methods, so I think it makes sense to move it to the beginning of the episode, possibly after creating the first neural network. This is how we did it when teaching it last time and it worked quite nicely.

**Comment by florian-huber** [comment]
I now moved it forward in episode 3 --> #113
