### ISSUE TITLE
check installation on Mac

### ISSUE THREAD

**Issue by dafnevk** [carpentries-incubator/deep-learning-intro#138]
When teaching this lesson, we had some Mac users run into issues with their tensorflow installation, the kernel would die. It seems related to this: https://medium.com/codex/installing-tensorflow-on-m1-macs-958767a7a4b3

We need to check if the setup instructions are currently sufficient to avoid this issue.

**Comment by psteinb** [comment]
I will ask a collaborator.

**Comment by tobyhodges** [comment]
I have an M1 MacBook I could test this on, if you need another guinea pig.

**Comment by psteinb** [comment]
My collaborator gave this a shot and ended up in dependency hell using anaconda. Don't worry, I was able to revive her this morning. :wink: 
She got stuck with this:
```
$ conda install -c apple tensorflow-deps
```
It would be great if you, @tobyhodges or anyone else, could give this a whirl just to have a second pair of eyes looking at this. 
Our current view of the matter is: it is simply not possible right now to have `tf` on Apple's M1 machines using anaconda.

**Comment by tobyhodges** [comment]
I installed Anaconda, created a new environment (a step I think you should include in your setup instructions!), and tried to follow https://carpentries-incubator.github.io/deep-learning-intro/setup/

```bash
 conda install "tensorflow>=2.5" seaborn "scikit-learn>=0.22" pandas
```

gave me

```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - tensorflow[version='>=2.5']

Current channels:

  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

so I tried installing via `pip` instead:

```
conda install pip
pip install tensorflow>=2.5 seaborn scikit-learn pandas
```

That _appeared_ to work, but when I opened Jupyter and ran

```python
import sklearn
print('sklearn version: ', sklearn.__version__)

import seaborn
print('seaborn version: ', seaborn.__version__)

import pandas
print('pandas version: ', pandas.__version__)

from tensorflow import keras
print('Keras version: ', keras.__version__)
```

the kernel crashed every time I tried to import `keras`. I ran the other imports in individual cells and they worked fine, so I am sure it was `from tensorflow import keras` that is causing the issue.

This was on a MacBook Air M1 from 2020, running macOS 11.4.

**Comment by Mahnoo06** [comment]
Hi @tobyhodges, the exact same thing happened to me yesterday when I tried to install it. However I was able to finally install and import Tensorflow  today. And I used a MacBook Pro with macOS 12.1.
- I used the following [tutorial ](https://github.com/jeffheaton/t81_558_deep_learning/blob/master/install/tensorflow-install-mac-metal-jul-2021.ipynb
)which I found super helpful. All the steps here are well documented and has a [YouTube video ](https://www.youtube.com/watch?v=_CO-ND1FTOU) along with it as well. 
- Apart from that while going through this endeavour  I learned a few things which might be useful for anyone and also when going through the above tutorial. 
    - I had to delete anaconda. My feeling is Anaconda is simply not optimized right now for M1 chips. It somehow disrupts the path variables and other things. Also "conda install anaconda-clean" did not work. So I had to delete everything manually. All the hidden files, folders and path variables I had to remove to make Miniforge and homebrew function properly.
    - Once Homebrew and Miniforge are installed. Write "which python" on your terminal and you should get something like: "/opt/homebrew/Caskroom/miniforge/base/bin/python". This turned out to be very important for my installation. As I could not move on to the next step unless  I had the right path so I had to fix my environment accordingly.
    - In this tutorial a virtual environment is created that has tensorflow with GPU support. All the dependencies are set in a yml file. However this yml file will automatically download with a .yml.txt extention on the Mac. This needs to be renamed to simply have .yml extension. It wont work otherwise.

**Comment by k-dominik** [comment]
Heya, just a quick note on the M1 setup:

```bash
mamba create -n tf -c apple -c conda-forge jupyter notebook pandas scikit-learn tensorflow-deps pip
mamba activate tf
pip install tensorflow-macos
pip install tensorflow-metal
```

ref: https://developer.apple.com/metal/tensorflow-plugin/

**Comment by svenvanderburg** [comment]
Things have gotten better in the meantime. With recent Anaconda/Miniconda versions you should have no problems installing Tensorflow with conda. But, students could still end up in M1 Mac setup hell, so I added #266
