### ISSUE TITLE
lesson03 teaching structure is an outlier

### ISSUE THREAD

**Issue by psteinb** [carpentries-incubator/deep-learning-intro#154]
I just taught lesson 03 (to a camera). I had to do multiple iterations because the lesson structure is driven by exercises rather than code blocks. Just wanted to mention that here - as both lesson 02 and lesson 04 do follow the carpentries template and use the exercises for self-study of the learners.

**Lesson 03 turns this around. The exercises contain the code blocks which are building the story.** That can be quite surprising if not irritating, when teaching.

**Comment by dafnevk** [comment]
As PR #169 solved this issue, I will close it.
