### ISSUE TITLE
Show wandb.ai weights and biases (under lesson 03-monitor)

### ISSUE THREAD

**Issue by cwmeijer** [carpentries-incubator/deep-learning-intro#157]
Wandb.ai is quite a game changer in terms of monitoring, debugging and logging the training processes. Especially beginners still have to create a habbit of logging what they ran exactly and with what hyperparameters, settings, code versions and dependencies etc they used and visualizing everything that might be of interest (losses, CPU/GPU/memory usages, correlations between settings and performances) in order to find errors in the training process early. Wandb.ai does all of this with very little effort from the user. Theoretically, this might not be so interesting for a course like this. But if we want to help attendees to actually start doing DL effectively, showing (not just mentioning) wandb.ai would be a very important addition.

Some alternative services/method to wandb.ai would also be fine. But I don't think there are any (and would be happy to learn otherwise).

**Comment by dsmits** [comment]
I think this is a very nice suggestion. On the other hand, we already have plenty of lesson material.

I wonder what @psteinb and @colinsauze think of this?

**Comment by colinsauze** [comment]
I think the description sounds like an advert.

**Comment by dsmits** [comment]
Just so you know @colinsauze ,@cwmeijer is a colleague of mine at the eScience center (so no representative of wandb.ai ;))
I haven't used wandb so far but I have seen it and it looks like it would help a lot.

@cwmeijer does a lot of deep learning projects and apparently the tool has transformed the way he works.

Since I don't have any experience with this tool I was curious what you guys would think about this suggestion, or whether there are similar tools or habits that you like to use that we should mention.

**Comment by colinsauze** [comment]
I have briefly encountered it myself and it did look quite useful. But the post read like somebody trying to sell it and my first thought was that somebody was trying to use this lesson to boost sales of a commercial product. 

Which actually raises the question about this being a commercial product. Their webpage says it is free for personal use, but does academic research count as personal use?

**Comment by dsmits** [comment]
Yeah it's not ideal that it's a commercial product. 
I quickly googled for alternatives and came accross [MLflow](https://mlflow.org/docs/latest/index.html) which is open source. Does @cwmeijer know about MLflow?

I'm giving it a try now while I'm going through the workshop material. I'll let you know if I think it's worth mentioning in the course.
Or would this type of tool be beyond the scope of the course?

**Comment by cwmeijer** [comment]
I didn't know about MLflow yet. I'll check it out later myself. Thanks! If it's similar then that would be preferable I'd say, because of it being open source.

At wandb.ai you can get a free academic license but you have to apply for it.

**Comment by colinsauze** [comment]
How much time do you think would be required to teach some basic use (and setup) of wandb during a workshop? We already have quite a lot of content, although I do wonder if this could save more time than it takes. 

Thinking more about the commercial aspect, there is some precedent in the carpentries lessons as the git lesson requires people to sign up for github.

**Comment by cwmeijer** [comment]
You would indeed get all plotting for free from the moment you set up wandb.
You would need to (from the top of my head):
- create an account at wandb.ai
- install a package ```pip install wandb``` and run ```wandb login```
- add about 3-5 lines of code indicating what model and what metrics to watch and the project name.
- log into the gui and browse around your results (after or during training)

I don't teach often so I don't know how that would translate into teaching hours. Would half an hour be realistic? You could possibly save some time skipping creation of matplotlib plots from then on.

**Comment by dsmits** [comment]
Another option would be to not make it an exercise but a demo. It might be preferable as it takes less time and the workshop is already packed content-wise.

I imagine it could be nice to show it at the end of the workshop so people can get an impression of how this could help them.

**Comment by dsmits** [comment]
I agree that it is very important to structure your deep learning training but since the workshop is already packed I don't think it is within the scope, so I'm closing this issue now.
