### ISSUE TITLE
Inconsistency between use of full and light datasets in monitoring the training process episode 

### ISSUE THREAD

**Issue by colinsauze** [carpentries-incubator/deep-learning-intro#160]
Some of the examples and output are from the full version of the weather set data and others are from the light version. For example the command to download the dataset within pandas is using the light version, but the hyperlink given just before is the full version. 

This does cause the output shown in the notes to differ from what the instructor/students will have in a few places.

**Comment by dsmits** [comment]
Related: #105

**Comment by dsmits** [comment]
I'll remove all references to the full dataset
