### ISSUE TITLE
Add small exercise to compute forward pass through single perceptron

### ISSUE THREAD

**Issue by dsmits** [carpentries-incubator/deep-learning-intro#164]
Since the perceptron is the essential building block I think it will help a lot to take the participants through the calculation of a single forward pass of a perceptron (plus activation function).

I think this will help the participants getting a firmer grip on the concepts introduced after this

**Comment by psteinb** [comment]
Do you mean, calculating everything by hand e.g. with 3 inputs, 3 hidden neurons and 2 outputs? Or would you have calculating this using `ndarray`s in mind?

**Comment by dsmits** [comment]
I was thinking calculating everything by hand would help best with understanding what a neural net does.

**Comment by dsmits** [comment]
Duplicate of #250
