### ISSUE TITLE
Make exercises chapter 3 main content

### ISSUE THREAD

**Issue by dsmits** [carpentries-incubator/deep-learning-intro#165]
The code of the main material and the exercises in chapter 3 are dependent on one another.

This makes it difficult for participants to keep up when their solution to an exercise was different from the given solution.

All code that the main material is dependent on should be part of the main material and not of the exercises. Then we can create new exercises to replace the old ones.

It's possible that this is an issue in other chapters as well. I only checked up until 3 so far.

**Comment by dsmits** [comment]
But then what would we do as exercises?

**Comment by psteinb** [comment]
Completely agree, I have some exercises that we could injest here, from
https://deeplearning540.github.io/lesson06/content.html (for lesson 2)
https://deeplearning540.github.io/lesson08/content.html (for lesson 3)
https://deeplearning540.github.io/lesson09/content.html (for lesson 4)

Just added templates for lesson 2 and 4 in case that helps as well.
