### ISSUE TITLE
teaching this material

### ISSUE THREAD

**Issue by wikfeldt** [carpentries-incubator/deep-learning-intro#188]
Hi,

just want to inform here that a colleague and myself from ENCCS (https://enccs.se/) will be teaching a workshop next week where we'll use this material. The lesson is really pedagogical so looking forward to it.

I will send a PR with small improvements we find and will raise issues for any larger observations that need a discussion

Cheers,
Thor

**Comment by wikfeldt** [comment]
I'd be happy to do what's formally needed to move the lesson to beta

**Comment by tobyhodges** [comment]
Housekeeping note for the lesson developers: to adjust the life cycle stage of the lesson, change `life_cycle` to `beta` in `_config.yml`, and - via the GitHub interface - adjust the repository topic tags to remove `alpha` and add `beta`. I will then adjust things on my side and you should be good.

Beyond that, I recommend adding something to the home page of your lesson site, encouraging people who teach the lesson to provide feedback to you as issues in the repository. You can see an example on the Jekyll lesson: https://carpentries-incubator.github.io/jekyll-pages-novice/

Finally, for @wikfeldt and any others who want to beta pilot this lesson, we have some [templates and information in our community handbook](https://docs.carpentries.org/topic_folders/lesson_development/lesson_pilots.html) that I hope you will find helpful. Feel free to reach out (incubator at carpentries dot org) if you have any questions.

**Comment by dafnevk** [comment]
Thanks @wikfeldt for notifying us and providing feedback and PRs. I opened #200 for moving officially to beta, I will close this issue.
