### ISSUE TITLE
removing non-Basel cities from training in episode 3 improves performance slightly

### ISSUE THREAD

**Issue by wikfeldt** [carpentries-incubator/deep-learning-intro#189]
i tried removing all other cities than Basel from the training data in episode 3. This greatly reduces the amount of data of course, but the predictions improve a bit. 

I won't change anything before teaching this next week but I anticipate questions about why observations from all the other cities are included to predict sunshine in Basel. 
Is there an idea behind that?

**Comment by wikfeldt** [comment]
a new exercise in episode 3 is now added in #196 where participants can try removing other cities than Basel, add more years of data to the training set, and rerun the workflow

**Comment by dafnevk** [comment]
I really like this exercise! Gives the learners an opportunity to experiment themselves with the data.

**Comment by dafnevk** [comment]
I really like this exercise! Gives the learners an opportunity to experiment themselves with the data.
