### ISSUE TITLE
results from penguin classification not reproducible

### ISSUE THREAD

**Issue by wikfeldt** [carpentries-incubator/deep-learning-intro#193]
despite setting all random seeds as instructed in the lesson (`numpy.random`, `tensorflow.random` and `random_state` in `train_test_split`) i get different classification results:

<img width="373" alt="Screenshot 2022-02-21 at 10 29 11" src="https://user-images.githubusercontent.com/10846818/154927440-5e3696f1-cf4e-4b84-92d8-3eb435e0a5b9.png">

So the conclusions in the lesson drawn from the confusion matrix don't hold. 

Not sure why this is, but for future-proofing it's probably safest to not include specific conclusions in the lesson

**Comment by wikfeldt** [comment]
version info:
- `sklearn version:  1.0.1`
- `Keras version:  2.4.0`

**Comment by dafnevk** [comment]
Good point, apperently the random seeds are not enough to garantuee consistency over OS-es and versions. We should add a warning about this to the training material.

**Comment by psteinb** [comment]
@wikfeldt what OS was this?

**Comment by psteinb** [comment]
Great, I'll try to honor that in #233
