### ISSUE TITLE
more visual aids of the neural networks and data would be useful

### ISSUE THREAD

**Issue by wikfeldt** [carpentries-incubator/deep-learning-intro#197]
participant feedback received from ENCCS workshop.

There are for example standard visualisations that can be used to explain convolutional layers and maxpooling layers

**Comment by dafnevk** [comment]
Is this mostly about the different layers in episode 4, or also in the other episodes? And what visualizations of the data are currently lacking?

**Comment by dsmits** [comment]
This issue is stale, closing it.
