### ISSUE TITLE
consider refactoring episodes

### ISSUE THREAD

**Issue by wikfeldt** [carpentries-incubator/deep-learning-intro#199]
an emerging best practice in online workshops is to only do half-days because full days on Zoom is fatiguing. But the duration of the episodes makes it impossible to split the workshop nicely into two half-days - episode 3 needs to be split up.

One idea could be to start with a full end-to-end workflow using the penguin dataset, but then partition episodes 3 and maybe 4 to be more specific. Shorter episodes could for example focus on 
- monitoring training
- regularization
- hyperparameter tuning

Another argument would be that the episode titles "Monitor the training process" and "Networks are like onions" are vague, and more concrete titles would both help learners navigate the lesson before, during and after a workshop, and look better in a schedule on a workshop webpage so that potential participants get an idea about what the workshop contains.

**Comment by dafnevk** [comment]
Thanks for this suggestion. Note that @dsmits and others taught it in three morning sessions:
* day 1: episode 1 and 2
* day 2: episode 3
* day 3: episode 4

We discussed splitting the episodes earlier, see e.g. #79  and #83, they are currently indeed quite long. One reason we haven't done so up to now, is that we liked the 'flow' of one episode and did not see a natural way to split up, that would make the episodes stand-alone (that is, not depend on the code in the previous episode).
However, if you now run into the same issue it may be worth reconsidering. Do you have a more specific suggestion on where to split the current material? Or would you rearrange the whole lesson?

**Comment by colinsauze** [comment]
I've made a separate issue about the titles of the episodes since that is really a different thing to the structure.

**Comment by dsmits** [comment]
We will not change the structure for now.
