### ISSUE TITLE
Clarify train test and validation data

### ISSUE THREAD

**Issue by k-dominik** [carpentries-incubator/deep-learning-intro#202]
https://github.com/carpentries-incubator/deep-learning-intro/blob/2959e87389a374b48d376c66bfe9b874ad41d51f/_episodes/01-introduction.md?plain=1#L156

> Sometimes we'll also use a 3rd set known as a validation set to check our results after training is complete

validation data is used _during_ training, e.g. in ep03

https://github.com/carpentries-incubator/deep-learning-intro/blob/2959e87389a374b48d376c66bfe9b874ad41d51f/_episodes/03-monitor-the-model.md?plain=1#L540-L543

**Comment by dafnevk** [comment]
Agree, this needs to be phrased differently and explained better. Related to issue #211 .
