### ISSUE TITLE
Update contributors lists

### ISSUE THREAD

**Issue by dafnevk** [carpentries-incubator/deep-learning-intro#205]
The list of contributers in README is outdated

**Comment by colinsauze** [comment]
I think it's the maintainers that is outdated. I'm presuming that @annefou @bpmweel and @florian-huber shouldn't be listed any more? Everyone who contributed will still be listed in the authors page. 
@dsmits is missing from both lists.

**Comment by annefou** [comment]
yes. I am not a maintainer of this lesson. Thanks.

**Comment by colinsauze** [comment]
@samumantha also made some contributions to early versions of the lesson and isn't currently credited in the authors page.
