### ISSUE TITLE
Image in introduction is broken

### ISSUE THREAD

**Issue by dafnevk** [carpentries-incubator/deep-learning-intro#209]
As noted in #207 , the first image in the Introduction episode is broken.

**Comment by colinsauze** [comment]
I presume this is the AI/ML/DL diagram? If so, it is showing for me.

**Comment by dsmits** [comment]
Weird, it is showing for me as well

**Comment by dafnevk** [comment]
It shows again for me to, no idea what the issue may have been but I will close this issue for now.
