### ISSUE TITLE
Demonstrate tensorboard

### ISSUE THREAD

**Issue by dafnevk** [carpentries-incubator/deep-learning-intro#223]
Many of the plots we manually create in the episodes, are also available in tensorboard.
If it's only a few lines of code, we can demonstrate how to track the training process in tensorboard. For example at the end of episode 3.

See [here](https://www.tensorflow.org/tensorboard/get_started) on how to run tensorboard from a notebook.

**Comment by dafnevk** [comment]
I'm interested to hear others opinions on whether we should include tensorboard in the material.
My feeling is that this should be optional, because it does take some time to show and explain tensorboard. It's very useful though, and really only a few lines of code. We can also add it as a call-out box.

**Comment by psteinb** [comment]
I’d support this 100%. It might be well worth considering a call-out rather early on this. In a call-out, following suit is framed to be optional.
