### ISSUE TITLE
Figure out licensing for existing images

### ISSUE THREAD

**Issue by dsmits** [carpentries-incubator/deep-learning-intro#228]
Check whether the images we are using are CC0.
If not, check we are allowed to publish these images in our CC0 licensed lesson material.

Incomplete list:
- [x] Penguin images (not CC0, but we are allowed to use it if we cite the creator)
- [x] Map in chapter 3 (based on BaseMap of maplotlib which is MIT, I think it's ok)
- [x] [Perceptron image in chapter one](https://carpentries-incubator.github.io/deep-learning-intro/fig/01_neuron.png)
- [x] Chapter 4 cameraman image (CC BY 4.0), we have to mention the creator
- [x] Images explaining convolution

**Comment by colinsauze** [comment]
> Can somebody tell me what's the source of the [perceptron image in chapter one](https://carpentries-incubator.github.io/deep-learning-intro/fig/01_neuron.png)? @colinsauze @psteinb @dafnevk ?

It is from the slide deck supplied by @bpmweel in issue #121 https://github.com/carpentries-incubator/deep-learning-intro/issues/121#issuecomment-877120353

**Comment by dsmits** [comment]
And do you know the source of the perceptron images in chapter 1?

**Comment by dafnevk** [comment]
I don't know about that one.

**Comment by colinsauze** [comment]
See above about the slides from Berend.

**Comment by bpmweel** [comment]
I created the image myself for this project, so I think we should add a license somehow. I wouldn't mind if it was CC0

**Comment by dafnevk** [comment]
It seems like we need to replace the cameraman image, they replaced it in skimage because of [licensing issues](https://github.com/scikit-image/scikit-image/issues/3927).
I created issue #243 .

**Comment by dsmits** [comment]
We just need to check the convolution image now

**Comment by dsmits** [comment]
I did a reverse image search for the convolution images. Only our workshop popped up so for now I'm assuming that they have been created by us.
