### ISSUE TITLE
Choice of capitalizing deep learning

### ISSUE THREAD

**Issue by qualiaMachine** [carpentries-incubator/deep-learning-intro#241]
I know this is a minor point, and apologies in advance for potentially starting a syntax war, but I'm not sure I agree with the choice of capitalizing "Deep Learning" throughout the lesson. Deep learning isn't a proper noun, and it typically isn't capitalized in research papers.

**Comment by dsmits** [comment]
Good point, thank you!

**Comment by dsmits** [comment]
I just noticed that in our [contributing guidelines](https://github.com/carpentries-incubator/deep-learning-intro/blob/gh-pages/CONTRIBUTING.md) we say we want to capitalize Deep Learning.
I wasn't there when the choice was made.
@psteinb or @colinsauze do you know why the choice was made for capitalizing Deep Learning?

**Comment by svenvanderburg** [comment]
@psteinb or @colinsauze ?

**Comment by colinsauze** [comment]
I can't remember what the reasoning was, I think we might have arbitrarily picked one way after realising that we had a inconsistency.

**Comment by svenvanderburg** [comment]
Conclusion: lowercase deep learning
