### ISSUE TITLE
Use jupyter lab instead of jupyter notebook

### ISSUE THREAD

**Issue by svenvanderburg** [carpentries-incubator/deep-learning-intro#245]
At the escience center we usually teach with jupyter lab instead of jupyter notebook. It is more modern and you have more overview (handy for teacher and participant). Could we change the setup instructions to use jupyter lab instead of jupyter notebook? (see https://github.com/esciencecenter-digital-skills/workshop-metadata/pull/31/files for what needs to be changed).

**Comment by dsmits** [comment]
Sounds good to me

**Comment by annajiat** [comment]
I would like to vote for tabbed alternatives so that workshops could choose either. Increases maintenance work though.

**Comment by svenvanderburg** [comment]
@annajiat this would possibly create confusion for participants right? They wouldn't know what to choose. I suggest to have setup instructions for a sensible default (of course I vote for jupyter lab.. 😇) and otherwise workshop instructors can supply their own instructions.

**Comment by dsmits** [comment]
@colinsauze @psteinb do you use jupyter lab or notebook?

**Comment by CunliangGeng** [comment]
I vote for jupyter lab. It has broader and more compact view, it's much easier to change cell from python to markdown and to view local files.

**Comment by dsmits** [comment]
Let's just do this. I think nobody would mind. We have to make sure that jupyter lab is mentioned in the setup instructions as well.
