### ISSUE TITLE
Improvements for episode 3 from teaching

### ISSUE THREAD

**Issue by svenvanderburg** [carpentries-incubator/deep-learning-intro#253]
@dafnevk made some suggestions for improvements after teaching episode 3:
- Variable naming is not ideal 
- Simplify the code. There's a lot of plotting  boilerplate, but also unnecessary options like verbose, batch_size, etc 
- Put compile model, and plotting results into function? Have to do a lot of copypasting now 
- I skipped the ‘try out metrics’ exercise, didn't seem necessary 

We can use [dafne's notebook](https://github.com/esciencecenter-digital-skills/2022-09-26-ds-dl-intro/blob/main/files/03-monitor-the-model.ipynb) for inspiration

**Comment by dsmits** [comment]
Related: #117

**Comment by cpranav93** [comment]
I think someone who has taught this episode is better suited to do the changes suggested. At a first look, things look simple from a code perspective to me.
