### ISSUE TITLE
Create a project

### ISSUE THREAD

**Issue by svenvanderburg** [carpentries-incubator/deep-learning-intro#261]
We would like a [Github Project](https://docs.github.com/en/issues/planning-and-tracking-with-projects) to track work in this repository. Unfortunately projects are nowadays created at the organisation level, so I cannot create it myself, I don't have the rights to do so. @tobyhodges @alex-konovalov @BatoolMM @davanstrien @klbarnes20 @lauzikaite could you create a project for us called 'deep-learning-intro planning & tracking'. You can do this here: https://github.com/orgs/carpentries-incubator/projects

Thanks a lot in advance 🙏

**Comment by tobyhodges** [comment]
@svenvanderburg I have created the project and made you an administrator so you can invite your collaborators.

**Comment by svenvanderburg** [comment]
Thanks a lot @tobyhodges ! 🙏 👍 I don't like the new projects... For some reason I cannot add the deep learning collaborators to the project... I've mentioned this [here](https://github.com/community/community/discussions/5874#discussioncomment-4261020)

**Comment by svenvanderburg** [comment]
@tobyhodges can you make the project public so at least everyone can see it?

**Comment by tobyhodges** [comment]
Done @svenvanderburg
