### ISSUE TITLE
Progressing from 'beta' to 'stable' stage

### ISSUE THREAD

**Issue by svenvanderburg** [carpentries-incubator/deep-learning-intro#262]
The lesson should progress from 'beta' stage to 'stable' stage. See https://carpentries.github.io/curriculum-development/the-lesson-life-cycle.html.

- [x] #178 
    - #284
- [x] feedback from beta pilot testers is incorporated
- [ ] #264

**Comment by svenvanderburg** [comment]
@tobyhodges can you specify:
* How many beta pilot testers we need
* Is this everything we still need to do?
* What is the final action for progressing this to the next stage?

**Comment by tobyhodges** [comment]
> * How many beta pilot testers we need

For official lessons, we run at least two beta pilot workshops before proposing that a curriculum/lesson be granted stable status. [That is also the requirement before a community-developed lesson can be submitted to The Carpentries Lab](https://github.com/carpentries-lab/reviews#what-makes-a-lesson-a-good-candidate-for-the-carpentries-lab).
 
> * Is this everything we still need to do?

Pretty much. But there is more you can do if you want to make the lesson even better - see below.
  
> * What is the final action for progressing this to the next stage?

It depends on what you determine the next stage to be. 

My _recommendation_ is to submit the lesson for [open peer review in The Carpentries Lab](https://github.com/carpentries-lab/reviews), which you can do as soon as you have feedback from at least two beta pilots. 

If you choose to do that, you have the option to also submit the lesson to [the Journal of Open Source Education](https://jose.theoj.org/) at the same time. If you want to do that, [you will need to write a `paper.md` file to accompany the lesson](https://openjournals.readthedocs.io/en/jose/submitting.html#how-to-prepare-a-learning-module-submission).

However, if you do not want to submit the lesson to the Lab, you are free to mark it stable any time you like. To do that, you can adjust the `life_cycle` field in `_config.yml` and the repository tags in the "About" box of the repository homepage.

**Comment by dsmits** [comment]
Related: #178

**Comment by svenvanderburg** [comment]
@colinsauze and @psteinb we thought it would be best to submit the lesson to Carpentries Lab. How do you feel about that?

**Comment by svenvanderburg** [comment]
Lesson marked as stable with #371, submission to carpentries lab will done with #333
