### ISSUE TITLE
Rename step 9. hyperparameter tuning to 9. Refining the model

### ISSUE THREAD

**Issue by cpranav93** [carpentries-incubator/deep-learning-intro#270]
Quoting @svenvanderburg from #268:
"Like we discussed I feel it would more sense to rename this step to 'Refine the model'.

I think in machine learning practice hyperparameter tuning or hyperparameter optimization is an automated process of finding the best hyperparameters. The simplest way to to this is a grid search. See https://en.wikipedia.org/wiki/Hyperparameter_optimization

'Refining the model' would feel better in this case, because we are manually changing hyperparameters of the model (with a conceptual framework in mind). Of course the automated hyperparameter tuning is a subset of 'finetuning the model'.

If you agree, you can create an issue for renaming this step everywhere in the lesson material." 

I think he has a point that the statement hyperparameter tuning can mean different things to different users. So we can change this to refining the model across all the episodes which would then have hyperparameter tuning contained within. Thoughts? @dsmits, @CunliangGeng

**Comment by CunliangGeng** [comment]
I like the new name `Refine the model`, which could contain changing architecture, tuning hyperparameters, using more data...
