### ISSUE TITLE
Improve solution to exercise: simplify the model and add data in episode 3

### ISSUE THREAD

**Issue by dsmits** [carpentries-incubator/deep-learning-intro#282]
In the [exercise to simplify the model and add data](https://carpentries-incubator.github.io/deep-learning-intro/03-monitor-the-model/index.html#exercise-simplify-the-model-and-add-data) there is a lot of duplicate code in the solution that will lead to a messy notebook.

I think we should show the right example and turn the whole process of selecting the dataset, the training and plotting the data into a function because we are doing the same thing multiple times in this exercise with only slightly different parameters.

**Comment by svenvanderburg** [comment]
Also relates to #332
