### ISSUE TITLE
Upload slides

### ISSUE THREAD

**Issue by dsmits** [carpentries-incubator/deep-learning-intro#302]
It's nice to teach with slides. I'll upload the slides I used.

**Comment by qualiaMachine** [comment]
@dsmits Sorry to resurrect an old thread, but did you ever end up adding those slides somewhere to this repo? I can't seem to find them. I also have some slides I used last time I taught this so no worries if you can't find them.

**Comment by svenvanderburg** [comment]
@qualiaMachine no, they are not here yet. I also have some slides :) https://nlesc-my.sharepoint.com/:p:/g/personal/s_vanderburg_esciencecenter_nl/ESXlVawOwDRCuW302YgjlCIBCd_-WCrvv2j1CiHG0NWljA?e=oBivu3 Not everything in there is open source though, but feel free to use them.

**Comment by qualiaMachine** [comment]
Awesome, thanks @svenvanderburg!

**Comment by qualiaMachine** [comment]
In the spirit of sharing, here are my slides from teaching this workshop a couple weeks ago: https://docs.google.com/presentation/d/1xC70nb3tKQMBjK0naKwdOzdETzlSnAtGx6OxNB3C408/edit?usp=sharing. Anyone is welcome to use them.
