### ISSUE TITLE
Update version numbers resulting from installs

### ISSUE THREAD

**Issue by colinsauze** [carpentries-incubator/deep-learning-intro#320]
The version numbers reported in the "Installing Keras and other dependencies" episode are old now.

I get the following under Python 3.11

sklearn version:  1.2.1
seaborn version:  0.12.2
pandas version:  1.5.3
Keras version:  2.12.0
Tensorflow version:  2.12.0-rc1

We should update this to reflect newer versions.

**Comment by miguel-mx** [comment]
Hi! I'm looking for my first Carpentries issue, it would be great if I can help you update this episode. 
Is this at the end of the /01-introduction.md?

**Comment by svenvanderburg** [comment]
@miguel-mx that's great! Welcome to the community 👋 Yes indeed it's here: https://github.com/carpentries-incubator/deep-learning-intro/blob/gh-pages/_episodes/01-introduction.md#testing-keras-installation and https://github.com/carpentries-incubator/deep-learning-intro/blob/gh-pages/setup.md#check-your-setup

**Comment by svenvanderburg** [comment]
I am looking forward to a pull request! Let us know if you need any help :)

**Comment by svenvanderburg** [comment]
Thanks @miguel-mx for your contribution. You are more than welcome to contribute more if you want :)
