### ISSUE TITLE
Make sure missing glossary definitions are added to glossario

### ISSUE THREAD

**Issue by dsmits** [carpentries-incubator/deep-learning-intro#323]
We're referring to [glossario](https://glosario.carpentries.org/) for definitions.

Some of the terms in our glossary are not in [glossario](https://glosario.carpentries.org/). It's best to get them included there rather than adding the definitions in just this lesson.

I've opened an issue there: https://github.com/carpentries/glosario/issues/576

**Comment by dsmits** [comment]
Awaiting merge of pr https://github.com/carpentries/glosario/pull/584

**Comment by svenvanderburg** [comment]
This is fixed now with https://github.com/carpentries/glosario/pull/598
