### ISSUE TITLE
Add neuron equation in introduction

### ISSUE THREAD

**Issue by carschno** [carpentries-incubator/deep-learning-intro#329]
In the introduction, the first exercise is to compute values from actual data. The required equation should be mentioned in the explanation of a neuron.

**Comment by ssterrett** [comment]
You could add the following to the [source code](https://github.com/carpentries-incubator/deep-learning-intro/blob/gh-pages/_episodes/01-introduction.md?plain=1#L74)
$Output =ReLu ( \sum x_i*w_i + bias)$

**Comment by svenvanderburg** [comment]
Closed with #377
