### ISSUE TITLE
Tensorflow instructions for M1 Macbooks not working

### ISSUE THREAD

**Issue by carschno** [carpentries-incubator/deep-learning-intro#330]
The installation of `tensorflow-macos` does not work (on some systems), needs to be investigated.

```
% pip install tensorflow-macos
ERROR: Could not find a version that satisfies the requirement tensorflow-macos (from versions: none)
ERROR: No matching distribution found for tensorflow-macos
```

**Comment by carschno** [comment]
Related thread: https://developer.apple.com/forums/thread/683757

**Comment by carschno** [comment]
Might be related to the Python version.

**Comment by svenvanderburg** [comment]
@carschno is this still an issue and how can we reproduce this? What kind of systems is this happening on?
