### ISSUE TITLE
Test run @ UW-Madison in May. Seeking schedule recommendations.

### ISSUE THREAD

**Issue by qualiaMachine** [carpentries-incubator/deep-learning-intro#331]
We're planning to run this workshop at UW-Madison on May 30 - June 1st, 9am-12:30pm CT. We're padding the schedule with a few extra hours (10.5 hrs total) just in case it's needed for intro/closing slides and occasional 10-min breaks. Does that sound like a reasonable schedule to those who have taught this before? 

Looking forward to it. Thanks.

**Comment by svenvanderburg** [comment]
Great! Good luck running the workshop. Let us know if you need anything :)

**Comment by svenvanderburg** [comment]
Feedback from this test run is in: #348
