### ISSUE TITLE
Mistake in Perceptron plot in Intro episode

### ISSUE THREAD

**Issue by bmcandr** [carpentries-incubator/deep-learning-intro#41]
Hello,

I was working through [the Introduction](https://github.com/carpentries-incubator/deep-learning_intro/blob/gh-pages/_episodes/01-introduction.md) and noticed that in the example code that is supposed to plot the "Perceptron" predictions, the colors in the figure are set on the encoded species label and *not* on the predictions made by the simple perceptron model. In fact, the `predict()` function defined in an earlier block of source code is never used. I've copied the code example below and added a comment on the line that should be addressed.

(and thanks for your work on this lesson!)

----

And finally, we are ready to apply our neural network to our dataset!

```python
import matplotlib.pyplot as plt
%matplotlib inline

eta = 0.1

# make 10 iterations
epochs = 10

[weights, errors] = train(x, y, eta, epochs)
print('Weights: %s' % weights)
plt.scatter(df.iloc[0:100, 0],df.iloc[0:100, 2], c=y)             # <-- change to c=predict(x, weights)?
plt.title('Perceptron')
plt.xlabel('sepal length [cm]')
plt.ylabel('petal length [cm]')
plt.show()

plt.plot(range(1, len(errors)+1), errors, marker='o')
plt.xlabel('Iterations')
plt.ylabel('Misclassifications')
plt.show()
...
```

**Comment by annefou** [comment]
We are closing this issue as we are completely rewriting the lesson. Thanks.
