### ISSUE TITLE
Episode 1: introduction to Deep Learning

### ISSUE THREAD

**Issue by dafnevk** [carpentries-incubator/deep-learning-intro#42]
## Learning objectives: 
- State for which problems Deep learning is a useful tool 
- List the available tools for Deep Learning 
- List the steps of a Deep Learning workflow 

## Questions: 
- What is deep learning? 
- When is it used and not used? 
- When is it successful? 
- What are the tools involved? 
- Why we chose Keras (Mention other tools )
- What is the workflow for deep learning? 

For this course, we focus on classification tasks.

**Comment by HaoZeke** [comment]
Given the API similarities, would it be appropriate/desirable to have accordion style tabs for the same model in PyTorch? I'd be happy to convert.

**Comment by dafnevk** [comment]
@HaoZeke I'd say it's not a priority, as learners who are new to Deep learning probably don't have a strong preference for one DL framework over the other. But as soon as we have the material a bit more worked out, we can reconsider whether it's worth the effort to convert to pytorch. I can image it would require somewhat more explanation around the pytorch code, because pytorch is still a bit more low-level than Keras.
