### ISSUE TITLE
Outlook still refers to cifar-10 instead of dollarstreeet

### ISSUE THREAD

**Issue by svenvanderburg** [carpentries-incubator/deep-learning-intro#461]
outlook [refers to cifar-10](https://github.com/carpentries-incubator/deep-learning-intro/blob/main/episodes/6-outlook.Rmd#L97) in a way that I think should be swapped to dollarstreet

**Comment by carschno** [comment]
I noticed a couple of inconsistencies in the dataset spelling too, will fix them as well.
