### ISSUE TITLE
Explain one-hot encoding in episode 2?

### ISSUE THREAD

**Issue by svenvanderburg** [carpentries-incubator/deep-learning-intro#488]
From @mike-ivs comments:

- a question that was raised a few times when we delivered this lesson in past workshops was "why do we use 3 columns of 0/1 instead of just one column 0/1/2 for the 3 labels?" i.e. why one-hot instead of label encoding (without knowing the names)
- It might be worth elaborating on why we want to "make things more complex" via one-hot encoding i.e. discuss the "ranking issue" of label encoding.
- This may slow things down due to extra detail, but this was a point where we risked our learners falling behind without a proper explanation.

**Comment by svenvanderburg** [comment]
@mike-ivs thanks for your comment! 

My thoughts:
1. We assume basic machine learning knowledge as a prerequisite, so not sure if we should go into details here.
2. Of course sometimes leaners ask this question. But in this case I would say it is one of the 1000 possible questions learners might ask and I am not sure if we should tackle all of them in the lesson content. I think in this case the instructor has enough information to answer the question.

**Comment by mike-ivs** [comment]
Fair points! Probably more a sign of our own workshop delivery than the lesson itself, feel free to close this change :)
(we've delivered this DL lesson the day after another ML lesson which doesn't cover encoding)

**Comment by svenvanderburg** [comment]
Cool! I'll close then.
