### ISSUE TITLE
Model training takes time

### ISSUE THREAD

**Issue by dafnevk** [carpentries-incubator/deep-learning-intro#53]
Some of the models might take a while to train. E.g. training 10 epochs on the cifar10 datasets takes 20 minutes on my laptop. That's still acceptable for a tutorial, but how to deal with this in a workshop setting? Maybe the episodes can be set up in a way that you can do explaining and non-coding exercises while waiting for the training results.
Any other ideas on this? What is the maximum training time we find acceptable?

**Comment by svenvanderburg** [comment]
I would say that is not acceptable, even not for a tutorial. Maybe it takes 20 minutes on your laptop, but on someone else's laptop it might take 2 hours.

I would say waiting for a minute max is acceptable.

A solution would be to use GPU, for example using [fast.ai google colab setup](https://course.fast.ai/start_colab#Using-a-GPU).
