### ISSUE TITLE
Another carpentries inspired intro to DL

### ISSUE THREAD

**Issue by psteinb** [carpentries-incubator/deep-learning-intro#54]
https://deapsecure.gitlab.io/deapsecure-lesson04-nn/index.html

Close this issue at will.

**Comment by wikfeldt** [comment]
and here are two more (inter-related) lessons:
https://hsf-training.github.io/hsf-training-ml-webpage/
https://hsf-training.github.io/hsf-training-ml-gpu-webpage/

the focus seems to be on traditional (shallow) ML methods though
