### ISSUE TITLE
Update lesson template used

### ISSUE THREAD

**Issue by psteinb** [carpentries-incubator/deep-learning-intro#61]
this site is currently build using travis. I'd appreciate any help updating the lesson template which among other things would build the site with github actions.

**Comment by psteinb** [comment]
I'd need some help on this.

**Comment by dafnevk** [comment]
I don't know what is needed to update the whole lesson to the newer template, but for github actions we can maybe copy the workflow files from https://github.com/carpentries/lesson-example/tree/gh-pages/.github/workflows

**Comment by psteinb** [comment]
That's the thing, I am also unclear how to best have this lesson be streamlined with the template: copy over files? git-submodules? Maybe @tobyhodges knows?

**Comment by tobyhodges** [comment]
Unless you plan to make significant customisations from the lesson template, I would suggest to swicth to using the remote theme. This will load the styling, page layouts, etc from https://github.com/carpentries/carpentries-theme, which is then kept up-to-date with the latest changes. Your repository will still need the GitHub Actions workflows, the `Makefile`, and a few others. I find it useful to have a local version of the `_includes/links.md` file for shared linkrefs throughout the site. Happy to prepare a PR if you would like me to help get you set up with this?

**Comment by psteinb** [comment]
@tobyhodges it would help me greatly going forward, if you could send the PR.
