### ISSUE TITLE
Fix website build

### ISSUE THREAD

**Issue by dafnevk** [carpentries-incubator/deep-learning-intro#64]
With the addition of graphviz as an dependency in PR #60 , the website [does not build](https://github.com/carpentries-incubator/deep-learning-intro/runs/2087381037) on gh-pages, even though the GH actions workflows are succesful.  The error mentions that: "The tag `graphviz` on line 140 in `_extras/design.md` is not a recognized Liquid tag."

**Comment by tobyhodges** [comment]
Re-posting my recommendation from #60 here: 

> For now, I recommend that you revert the changes to the Actions workflow and comment out this part of the Design Notes page, ready to re-introduce it if and when a future version of the lesson template supports this kind of diagram.
