### ISSUE TITLE
Use weather prediction dataset for episode 2

### ISSUE THREAD

**Issue by dafnevk** [carpentries-incubator/deep-learning-intro#80]
In order to reduce cognitive overload and teaching time, we could use the [weather prediction dataset](https://github.com/florian-huber/weather_prediction_dataset) for episode 2 as well. Use it for binary classification, if this is added as a column according to issue https://github.com/florian-huber/weather_prediction_dataset/issues/8.

**Comment by bpmweel** [comment]
The context switch between the different datasets helped learners to rethink about what they learned in episode 2, so the two datasets actually helped with this.
