### ISSUE TITLE
Create visualization of convolutions

### ISSUE THREAD

**Issue by dafnevk** [carpentries-incubator/deep-learning-intro#81]
Episode 4 could use an illustration of what the effect is of applying convolutions with different kernels on an image. We can create an example with common 'classical' image processing filters.

**Comment by psteinb** [comment]
Alternatively, maybe we can lend/use something from this project:
https://github.com/vdumoulin/conv_arithmetic

or this project
https://github.com/dvgodoy/dl-visuals

What do you think?

**Comment by dafnevk** [comment]
Nice links, I'll have a look! Also maybe for a visual on pooling layers, or combining different layers in a convolutional neural network.

**Comment by bpmweel** [comment]
This was added in #58
