### ISSUE TITLE
improve software setup with a dedicated conda environment

### ISSUE THREAD

**Issue by psteinb** [carpentries-incubator/deep-learning-intro#89]
add using a specific conda environment, e.g. with 
```
conda create --name dl_pilot python=3.6 tensorflow seaborn scikit-learn pandas 
```
thanks @sstevens2

**Comment by sstevens2** [comment]
Might want to call it `dl_wkshp` or something for longevity after pilots

Maybe this is the final one but I was remembering that I missed something with my first time creating it and had to add something and run again to overwrite original env.  Can't remember what it was I had to add though so maybe it is already in the above line of code.

**Comment by psteinb** [comment]
The default installation method for `tf` has changed to `pip`. I guess we need to consider this.
https://www.tensorflow.org/install
