### ISSUE TITLE
append hints on how to use cloud based solutions for software

### ISSUE THREAD

**Issue by psteinb** [carpentries-incubator/deep-learning-intro#91]
in case people struggle with the local installation, a callout for the ready-made cloud instances is helpful

- [x] Add mention to google collab in setup instructions

**Comment by colinsauze** [comment]
There are some guides and links from the Carpentries on using My Binder/BinderHub for this at 
https://github.com/carpentries/scaffolds/blob/master/instructions/workshop-coordination.md#my-binder
