### ISSUE TITLE
Show function usage syntax for value_counts

### ISSUE THREAD

**Issue by yochannah** [carpentries-incubator/deep-learning-intro#95]
HERE: https://github.com/carpentries-incubator/deep-learning-intro/blame/gh-pages/_episodes/02-keras.md#L304  

showing the syntax to use (i.e. `y_train.value_counts()`) would make this step easier.

**Comment by dafnevk** [comment]
`y_train.value_counts()` does not even work I think, but the same result can be found with `y_train.sum()`
