### ISSUE TITLE
add visual for neural network before composing it in keras

### ISSUE THREAD

**Issue by psteinb** [carpentries-incubator/deep-learning-intro#98]
as recommended by our learners during the 20210622 trial teaching, a visual representation will help people build a concept before punching in the code

**Comment by colinsauze** [comment]
It would be really useful if there's a way we an visualise the network we build in the "Create the neural network" exercise. From a quick google search, Keras has a built in model plotting tool - https://keras.io/api/utils/model_plotting_utils/

**Comment by bpmweel** [comment]
In our recent workshop I just pasted the image I used in my introductory slides in a markdown cell, this worked very well.

Indeed perhaps doing the visualization using the model plot would show that the architecture indeed matches

**Comment by bpmweel** [comment]
Closing in favour of #125
